language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

env:
  - workerCount=3 timeout=600000
  - CODECOV_TOKEN="394696a3-d7da-4c13-b1c0-cc63c7940a4c"

matrix:
  fast_finish: true

branches:
  only:
  - master
  - /^release-.*/

install:
  - npm install

cache:
  directories:
    - node_modules
    
scripts:
  - nmp test
  - npm install codecov -g
after_success:
  - codecov